- name: play level varibles
  hosts: local
  connection: local
  vars_files:
    - variables.yaml
  tasks:
  - name: "Print the variables"
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Trainer is: {{ TRAINER }}"