# This program is to check the facts which are gathered by ansible and print the os family

- name: gathering facts
  hosts: local
  connection: local
  tasks:
    - name: print_facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: check the distribution is redhat or not
      ansible.builtin.debug:
        msg: "Yes the distribution is Redhat"
      when: ansible_facts.os_family == "RedHat"


