- name: install and remove
  hosts: local
  connection: local
  tasks:
  - name: loop the packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "nginx", state: "present" }
    - { name: "mysql", state: "absent" }
    - { name: "zip", state: "present" }